{% set name = "rogue" %}
{% set version = "v5.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-{{ version }}.tar.gz
  sha256: d07a944fd87598d7849d874458c67dd26a26e953720a423b60e79dfd3c8dc561

build:
  skip: True  # [win or osx]
  number: 5

requirements:
   build:
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
     - git
     - cmake
     - make
   host:
     - python
     - boost
     - bzip2
     - zeromq
     - epics-base=7.0.4 [linux]
     - pcas       [linux]
     - numpy
   run:
     - python
     - {{ pin_compatible('boost', min_pin='x.x', max_pin='x.x')}}
     - boost
     - bzip2
     - zeromq
     - epics-base=7.0.4 [linux]
     - pcas       [linux]
     - numpy
     - ipython
     - p4p        [linux]
     - pyyaml
     - jsonpickle
     - pyzmq
     - parse
     - click
     - pyqt
     - pyepics    [linux]
     - sqlalchemy
     - pydm
     - pyserial

about:
  home: https://github.com/slaclab/rogue
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'SLAC Python Based Hardware Abstraction & Data Acquisition System'
  description: |
    python-based hardware abstraction and data acquisition system
    for SLAC.
  doc_url: https://slaclab.github.io/rogue/
  dev_url: https://github.com/slaclab/rogue

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
